"""检索结果进入生成模型前的上下文组织能力。"""

from app.retrieval.context.packer import (
    ContextCandidate,
    ContextPackRequest,
    ContextPacker,
    ContextPackerConfig,
    ContextSegment,
    ContextSourceRange,
    ContextTokenUsage,
    DroppedChunk,
    PackedContext,
    TokenAwareContextPacker,
)
from app.retrieval.context.evidence_transformers import (
    EvidenceCandidate,
    EvidenceSource,
    EvidenceTransformRequest,
    EvidenceTransformResult,
    EvidenceTransformStage,
    EvidenceTransformStageResult,
    EvidenceTransformationConfig,
    EvidenceTransformer,
    EvidenceTransformerRegistry,
    PassthroughEvidenceTransformer,
    build_default_evidence_transformer_registry,
    passthrough_candidates,
)
from app.retrieval.context.token_estimators import (
    RegexTokenEstimator,
    TokenEstimator,
    TokenEstimatorConfig,
    TokenEstimatorRegistry,
    build_default_token_estimator_registry,
)

__all__ = [
    "ContextCandidate",
    "ContextPackRequest",
    "ContextPacker",
    "ContextPackerConfig",
    "ContextSegment",
    "ContextSourceRange",
    "ContextTokenUsage",
    "DroppedChunk",
    "PackedContext",
    "RegexTokenEstimator",
    "TokenAwareContextPacker",
    "TokenEstimator",
    "TokenEstimatorConfig",
    "TokenEstimatorRegistry",
    "build_default_token_estimator_registry",
    "EvidenceCandidate",
    "EvidenceSource",
    "EvidenceTransformRequest",
    "EvidenceTransformResult",
    "EvidenceTransformStage",
    "EvidenceTransformStageResult",
    "EvidenceTransformationConfig",
    "EvidenceTransformer",
    "EvidenceTransformerRegistry",
    "PassthroughEvidenceTransformer",
    "build_default_evidence_transformer_registry",
    "passthrough_candidates",
]
